### ISSUE TITLE
Explore UE and code thus far

### ISSUE THREAD

**Issue by haugeSander** [RIT-NTNU-Bachelor/Unreal-facetracking-client#26]

**Comment by marhjoh** [comment]
# Update 04/01/2024

I am currently following [Unreal Engine 5 – Full Course for Beginners](https://www.youtube.com/watch?v=6UlU_FsicK8) by freeCodeCam that covers the foundamentals for UE. Only watching what is of interest for our project.

**Comment by marhjoh** [comment]
# Update 04/01/2024 5 PM

@haugeSander explained the codebase to me as of now. I will further delve into UE, and will start working on more complex algorithms for FOV tomorrow.
