### ISSUE TITLE
Download necessary tools on prototype computer MCSL

### ISSUE THREAD

**Issue by haugeSander** [RIT-NTNU-Bachelor/Unreal-facetracking-client#27]
# What
The computer in the lab lacks several important software's for our MVP and prototype to work. We do not have admin privileges on these computers, therefore we need to apply for it.

- [x] Python interpreter
- [x] Unreal Engine 5.2.1
- [x] Visual studio 2022

### Idea
Store all on a USB drive, as we could easily move it between computers. Sander has a 128gb usb stick.
- Only python could be downloaded on the USB drive

**Comment by haugeSander** [comment]
## Update 01.04
Asked Mike for help.

**Comment by haugeSander** [comment]
# Update 02.04
Downloaded Python interpreter and Unreal Engine 5.2.1, as well as updated GPU driver. Does not have enough storage to download Visual Studio 2022.

**Comment by KjetilIN** [comment]
# Learnings/ Notes during setup: 

- Mediapipe was an error in the download script. No clue why. But it seems like it fixed itself. 
- Also need to **pip install cmake** to be able to build the dlib package (Install has to be better. Maybe removing the script is a good idea. Idk
- Used vscode and made it select the venv. Maybe include this on the setup section of the README file. 
- Could be an idea to have different `requirements.txt` files for different usecases. For instance, one with all of the jupiter stuff. IDK

**Comment by KjetilIN** [comment]
# Solution for setting up Python: 
- Use Python 3.10
- Create a new `venv` using VS code 
  - Select Python 3.10
  - Select `requirements.txt` as packages
  - Let it install everything

Then for any bugs, install the missing library within the pip command. (Must be within the venv, meaning that it has to be activated when installing the environment) ( I had to pip install mediapipe)

**Comment by KjetilIN** [comment]
In review. Not tested both UE and OpenCV server
