### ISSUE TITLE
Add blur when the user is out of FOV

### ISSUE THREAD

**Issue by KjetilIN** [RIT-NTNU-Bachelor/Unreal-facetracking-client#45]
# What?

When the user is out of the field of view of the camera, then the screen should be blurry to tell the user that the software is not support to be working anymore. 

The blur should be quite strong. We could also add a text that says "Out of focus".

**Comment by KjetilIN** [comment]
See PR #48

**Comment by haugeSander** [comment]
# Reopened
This only occurs in debug mode. Reopened to improve it.

**Comment by haugeSander** [comment]
PR #61
