### ISSUE TITLE
Create a release for v1.0.0 for all code repos

### ISSUE THREAD

**Issue by haugeSander** [RIT-NTNU-Bachelor/Unreal-facetracking-client#62]
# What?
Make a release of the final products.

- [x] Unreal Engine client
- [x] Python opencv server

To Do: 

- [x] Remove run all script 
- [x] Change the FOV based on case study 
- [x] Release OpenCV Server
- [x] Create last PR for Case Study
- [x] Release case study

**Comment by haugeSander** [comment]
# Released for UE Client
Check it out: https://github.com/RIT-NTNU-Bachelor/Unreal-facetracking-client/releases/tag/v1.0.0

**Comment by KjetilIN** [comment]
Blocked due to some scripts are not ready for release

**Comment by KjetilIN** [comment]
Working on the to-do list in the description

**Comment by KjetilIN** [comment]
Created pr for removing the run all script

**Comment by KjetilIN** [comment]
Created the final PR (https://github.com/RIT-NTNU-Bachelor/case-study/pull/9 ) in the Case Study repo. It is the final PR before creating a release. Please review when you have time @haugeSander and @marhjoh 

This issue is blocked until the PR is approved

**Comment by KjetilIN** [comment]
Created the release for the OpenCV Server! Added some comments to what features that the server has.

**Comment by KjetilIN** [comment]
Waiting for the final workflow to finish and then we can close this issue. After I have created a release for the case studies

**Comment by KjetilIN** [comment]
Done
